### ISSUE TITLE
How to use the Registration without GPU？

### ISSUE THREAD

**Issue by naledo** [brianlee324/torch-lddmm#3]
Hello! 
I am interested in the efficiency of gpu acceleration and I want to compare gpu version with cpu version.
How to use the lddmm registration without gpu？
Look forward to your reply.

**Comment by naledo** [comment]
'gpu_number = None' has worked.

**Comment by brianlee324** [comment]
Yep, setting gpu_number to None will default to CPU. I'll add that to the README.
